### ISSUE TITLE
jupyterlab missing in dependencies

### ISSUE THREAD

**Issue by pyongjoo** [illinoisdata/kishu#410]
I just installed Kishu in a fresh virtual environment.

When I launched jupyterlab with
```
jupyter lab
```
it starts but no "kishu" appears.

I ran
```
pip install jupyterlab
```
in the virtual environment.

Now, the "kishu" tab appears.

**Comment by mIXs222** [comment]
@BillyZhaohengLi Could you add `jupyterlab` to the dependency list in `jupyterlab_kishu/pyproject.toml`?

**Comment by BillyZhaohengLi** [comment]
Fixed with https://github.com/illinoisdata/kishu/pull/412
